version: '3'

services:
  api:
 
    build: ./api
    ports:
      - "5000:5000"
  web:

    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./www:/var/www/html